package org.ye.psys.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.ye.psys.db.entity.GoodsStock;
import org.ye.psys.db.entity.GoodsStockExample;

public interface GoodsStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     */
    long countByExample(GoodsStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     */
    int deleteByExample(GoodsStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     */
    int insert(GoodsStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     */
    int insertSelective(GoodsStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GoodsStock selectOneByExample(GoodsStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GoodsStock selectOneByExampleSelective(@Param("example") GoodsStockExample example, @Param("selective") GoodsStock.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<GoodsStock> selectByExampleSelective(@Param("example") GoodsStockExample example, @Param("selective") GoodsStock.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     */
    List<GoodsStock> selectByExample(GoodsStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GoodsStock selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") GoodsStock.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     */
    GoodsStock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GoodsStock selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GoodsStock record, @Param("example") GoodsStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GoodsStock record, @Param("example") GoodsStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GoodsStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodsStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") GoodsStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);

    int reduceStock(@Param("id") Integer stockId, @Param("left") int left);

    int addStock(@Param("id") Integer id, @Param("num") int num);
}