package org.ye.psys.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.ye.psys.db.entity.UserChart;
import org.ye.psys.db.entity.UserChartExample;

public interface UserChartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chart
     *
     * @mbg.generated
     */
    long countByExample(UserChartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chart
     *
     * @mbg.generated
     */
    int deleteByExample(UserChartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chart
     *
     * @mbg.generated
     */
    int insert(UserChart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chart
     *
     * @mbg.generated
     */
    int insertSelective(UserChart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserChart selectOneByExample(UserChartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserChart selectOneByExampleSelective(@Param("example") UserChartExample example, @Param("selective") UserChart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<UserChart> selectByExampleSelective(@Param("example") UserChartExample example, @Param("selective") UserChart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chart
     *
     * @mbg.generated
     */
    List<UserChart> selectByExample(UserChartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserChart selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") UserChart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chart
     *
     * @mbg.generated
     */
    UserChart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chart
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserChart record, @Param("example") UserChartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chart
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserChart record, @Param("example") UserChartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserChart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_chart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserChart record);
}